### PR TITLE
The maximum length for the user option 'profile.aboutMe' is 1000

### PR DESCRIPTION
**Pull request by MeinAccount**

### CODE REVIEW

**Comment by MeinAccount** [comment]
That was fast :smile:

**Comment by TimWolla** [comment]
> That was fast :smile:

Thank IMAP push!

**Comment by MeinAccount** [comment]
GitHub also seems to have some kind of inline updating.

**Comment by TimWolla** [comment]
> GitHub also seems to have some kind of inline updating.

Oh yeah, it does. Was annouced somewhere in the blog in the past.

**Comment by MeinAccount** [comment]
Oh yes, [you're right](https://github.com/blog/1174-auto-updating-comments). But that is almost a year ago...

**Comment by TimWolla** [comment]
It is almost 2 years, we live in 2014 ;)

**Comment by MeinAccount** [comment]
Whoops!

**Pull request merged**
