### PR TITLE
Update UserFaker.class.php

### PR DESCRIPTION
**Pull request by ghost**
UserFaker sets all users' lastActivityTime to 0. Meaning that those users never were logged in, although they might have been members for years. That is unrealistic and prevents you from seriously testing activity-related issues without creating session data or activities (posting, likes ...) for some of those users.

This modification sets lastActivityTime to random values between registrationDate and TIME_NOW or to 0, which results in a more reasonable mix of lastActivityTime values.

### CODE REVIEW

**Comment by TimWolla** [comment]
I don't like the current generation for the zero. Have a look at [the `optional()-modifier`](https://github.com/fzaninotto/Faker/#unique-and-optional-modifiers) and convert `null` to zero.

Thanks for your contribution!

**Comment by ghost** [comment]
Well, did it. However, lacking any experience with GitHub:
Do you see the change as an additional commit or are the (previous) commit and this change merged into a single commit?

**Comment by TimWolla** [comment]
> Do you see the change as an additional commit or are the (previous) commit and this change merged into a single commit?

Those are two independent commits, but I can squash them into a single one if I want to. One note: Please make sure to use a proper commit message in the future "Update UserFaker.class.php" tells nothing about the contents of the commit.

**Comment by TimWolla** [comment]
Should I merge this one, or do you want to create a new pull request with only a single commit?

BTW: I recommend to use an additional branch for every pull requests instead of using the `master` this makes it easier to update your version once mine changes, you'll probably have to recreate this repository because of this issue.

**Comment by ghost** [comment]
Well, before I screw it, I'd like you to do it ;-)

**Comment by TimWolla** [comment]
@UdoZa Done. I have rewritten the commit message as well. Thanks again!

fe0b852d8a0d6ee4905b8fb78168683ed2f08442

**Pull request closed without merging**
